#!/bin/bash

# mvregex - A bash script for batch moving a set of files given 2 regexes
#
# Copyright (c) 2013 Neal Hardesty
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

shopt -s nullglob
if [ "$1" = "-s" ]; then 
	SIMULATE=true
	shift
fi

OLDRE="$1"
shift
NEWRE="$1"
shift

if [ -z "$OLDRE" ]; then
	echo $0 - move a set of files from oldRegex to newRegex
	echo
	echo Usage: $0 [-s] '<oldRegex> <newRegex> [file1] .. [fileN]'
	echo    '-s -> simulate only'
	exit 255
fi

for file in "$@"; do
	newfile=`echo "$file" |sed -e "s/$OLDRE/$NEWRE/g"`
	if [ ! "$file" = "$newfile" ]; then
		if [ $SIMULATE ]; then
			echo SIM "$file" '->' "$newfile"
		else
			mv -v "$file" "$newfile"
		fi
	fi
done
